// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4Demo1.tt. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace ScribanSourceGeneratorDemo
{
static class T4Demo1
{
    public static void Parse(string s, out bool x) => x = bool.Parse(s);
    public static void Parse(string s, out byte x) => x = byte.Parse(s);
    public static void Parse(string s, out sbyte x) => x = sbyte.Parse(s);
    public static void Parse(string s, out short x) => x = short.Parse(s);
    public static void Parse(string s, out ushort x) => x = ushort.Parse(s);
    public static void Parse(string s, out int x) => x = int.Parse(s);
    public static void Parse(string s, out uint x) => x = uint.Parse(s);
    public static void Parse(string s, out long x) => x = long.Parse(s);
    public static void Parse(string s, out ulong x) => x = ulong.Parse(s);
    public static void Parse(string s, out float x) => x = float.Parse(s);
    public static void Parse(string s, out double x) => x = double.Parse(s);
    public static void Parse(string s, out DateTime x) => x = DateTime.Parse(s);
    public static void Parse(string s, out DateTimeOffset x) => x = DateTimeOffset.Parse(s);
    public static void Parse(string s, out TimeSpan x) => x = TimeSpan.Parse(s);
}}
